spring:
  h2:
    console:
      enabled: false
  datasource:
    password: 'password'
    username: 'admin'
    url: 'jdbc:h2:file:./db'
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
